using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MovJugador : MonoBehaviour
{

    public float velocidad = 15;
    public float velAngular = 60;

    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
        if (Input.GetKey(KeyCode.A))
        
        {
             transform.Translate(new Vector3(velocidad * Time.deltaTime,0, 0));
           // transform.Rotate(new Vector3(0, -velAngular * Time.deltaTime, 0));
        }
        if (Input.GetKey(KeyCode.D))
        {
            transform.Translate(new Vector3(-velocidad * Time.deltaTime,0, 0));
           // transform.Rotate(new Vector3(0, velAngular * Time.deltaTime, 0));
        }
        if (Input.GetKey(KeyCode.W))
        {
            transform.Translate(new Vector3(0, 0, velocidad * Time.deltaTime));
        }
        if (Input.GetKey(KeyCode.S))
        {
            transform.Translate(new Vector3(0, 0, -velocidad * Time.deltaTime));
        }



    }
}
